/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg4inrow;

/**
 *
 * @author human
 */
public class Gui extends javax.swing.JFrame {
    
    GameLogic gl = new GameLogic();

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_c1 = new javax.swing.JButton();
        btn_c2 = new javax.swing.JButton();
        btn_c3 = new javax.swing.JButton();
        btn_c4 = new javax.swing.JButton();
        btn_c5 = new javax.swing.JButton();
        btn_c6 = new javax.swing.JButton();
        btn_c7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_tablero = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_c1.setText("C1");
        btn_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c1ActionPerformed(evt);
            }
        });

        btn_c2.setText("C2");
        btn_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c2ActionPerformed(evt);
            }
        });

        btn_c3.setText("C3");
        btn_c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c3ActionPerformed(evt);
            }
        });

        btn_c4.setText("C4");
        btn_c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c4ActionPerformed(evt);
            }
        });

        btn_c5.setText("C5");
        btn_c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c5ActionPerformed(evt);
            }
        });

        btn_c6.setText("C6");
        btn_c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c6ActionPerformed(evt);
            }
        });

        btn_c7.setText("C7");
        btn_c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c7ActionPerformed(evt);
            }
        });

        txtArea_tablero.setColumns(20);
        txtArea_tablero.setRows(5);
        jScrollPane1.setViewportView(txtArea_tablero);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_c1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_c2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_c3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_c4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_c5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_c6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_c7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_c1)
                    .addComponent(btn_c2)
                    .addComponent(btn_c3)
                    .addComponent(btn_c4)
                    .addComponent(btn_c5)
                    .addComponent(btn_c6)
                    .addComponent(btn_c7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c1ActionPerformed
        // TODO add your handling code here:}
        gl.turno(0);
        txtArea_tablero.setText(gl.getTablero());
    }//GEN-LAST:event_btn_c1ActionPerformed

    private void btn_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c2ActionPerformed
        // TODO add your handling code here:
        gl.turno(1);
        txtArea_tablero.setText(gl.getTablero());
    }//GEN-LAST:event_btn_c2ActionPerformed

    private void btn_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c3ActionPerformed
        // TODO add your handling code here:
        gl.turno(2);
        txtArea_tablero.setText(gl.getTablero());
    }//GEN-LAST:event_btn_c3ActionPerformed

    private void btn_c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c4ActionPerformed
        // TODO add your handling code here:
        gl.turno(3);
        txtArea_tablero.setText(gl.getTablero());
    }//GEN-LAST:event_btn_c4ActionPerformed

    private void btn_c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c5ActionPerformed
        // TODO add your handling code here:
        gl.turno(4);
        txtArea_tablero.setText(gl.getTablero());
    }//GEN-LAST:event_btn_c5ActionPerformed

    private void btn_c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c6ActionPerformed
        // TODO add your handling code here:
        gl.turno(5);
        txtArea_tablero.setText(gl.getTablero());
    }//GEN-LAST:event_btn_c6ActionPerformed

    private void btn_c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c7ActionPerformed
        // TODO add your handling code here:
        gl.turno(6);
        txtArea_tablero.setText(gl.getTablero());
    }//GEN-LAST:event_btn_c7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_c1;
    private javax.swing.JButton btn_c2;
    private javax.swing.JButton btn_c3;
    private javax.swing.JButton btn_c4;
    private javax.swing.JButton btn_c5;
    private javax.swing.JButton btn_c6;
    private javax.swing.JButton btn_c7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea_tablero;
    // End of variables declaration//GEN-END:variables
}
